server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.52.170
      database: spitdb
  redis:
    host: 192.168.52.170
    port: 6379
  rabbitmq:
    host: 192.168.52.170
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true

