server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.52.170:3306/tensquare_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.52.170
    port: 6379
  rabbitmq:
    host: 192.168.52.170
jwt:
  config:
    # key代表盐  ttl过期时间
    key: wang
    ttl: 600000
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true